{"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/SValidator\/documentation\/SValidator\/ValidationError\/failedValidation"],"anchor":"Enumeration-Cases"},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/SValidator\/documentation\/SValidator\/ValidationError\/Equatable-Implementations"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"This enum helps identify the type of validation failure encountered during the validation process.","type":"text"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"failedValidation","type":"codeVoice"},{"text":": Represents a generic validation failure.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"customError","type":"codeVoice"},{"text":": Represents a custom error with an associated message.","type":"text"}]}]}]}]}],"hierarchy":{"paths":[["doc:\/\/SValidator\/documentation\/SValidator"]]},"sections":[],"identifier":{"url":"doc:\/\/SValidator\/documentation\/SValidator\/ValidationError","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/SValidator\/SQ","doc:\/\/SValidator\/s5ErrorP","doc:\/\/SValidator\/SH","doc:\/\/SValidator\/s8SendableP"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Represents the validation error encountered when a value fails validation."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/svalidator\/validationerror"]}],"metadata":{"navigatorTitle":[{"text":"ValidationError","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationError"}],"symbolKind":"enum","roleHeading":"Enumeration","role":"symbol","modules":[{"name":"SValidator"}],"title":"ValidationError","externalID":"s:10SValidator15ValidationErrorO"},"references":{"doc://SValidator/documentation/SValidator/ValidationError/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup","identifier":"doc:\/\/SValidator\/documentation\/SValidator\/ValidationError\/Equatable-Implementations","url":"\/documentation\/svalidator\/validationerror\/equatable-implementations","kind":"article"},"doc://SValidator/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/SValidator\/SQ"},"doc://SValidator/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/SValidator\/s8SendableP"},"doc://SValidator/documentation/SValidator/ValidationError/failedValidation":{"kind":"symbol","type":"topic","title":"ValidationError.failedValidation","url":"\/documentation\/svalidator\/validationerror\/failedvalidation","abstract":[],"identifier":"doc:\/\/SValidator\/documentation\/SValidator\/ValidationError\/failedValidation","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedValidation","kind":"identifier"}]},"doc://SValidator/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/SValidator\/SH"},"doc://SValidator/documentation/SValidator/ValidationError":{"title":"ValidationError","role":"symbol","navigatorTitle":[{"text":"ValidationError","kind":"identifier"}],"type":"topic","url":"\/documentation\/svalidator\/validationerror","kind":"symbol","abstract":[{"type":"text","text":"Represents the validation error encountered when a value fails validation."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationError","kind":"identifier"}],"identifier":"doc:\/\/SValidator\/documentation\/SValidator\/ValidationError"},"doc://SValidator/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/SValidator\/s5ErrorP"},"doc://SValidator/documentation/SValidator":{"kind":"symbol","identifier":"doc:\/\/SValidator\/documentation\/SValidator","title":"SValidator","abstract":[],"type":"topic","role":"collection","url":"\/documentation\/svalidator"}}}